#stage 1
FROM node:alpine3.10
WORKDIR /app
COPY auth-server.js .
COPY ./config ./config/
COPY ./controllers/authenticateTokenController.js ./controllers/
COPY ./models/userModel.js ./models/
COPY package.json .
COPY package-lock.json .
ARG MONGO_POS_URI
ARG STATUS
ARG ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET
ARG SESSION_SECRET
ARG STRIPE_SECRET
ARG POS_FRONTEND_URL

RUN npm ci
CMD ["node","auth-server.js"]
