back-end:
  image: api-server
  env_file:
    - .env
  expose:
    - "3000"
  ports:
    - "1000:3000"
  volumes:
    - ./config/passport-config.js:/config/passport-config.js

auth-end:
  image: auth-server
  env_file:
    - .env
  expose:
    - "4000"
  ports:
    - "2000:4000"
  volumes:
    - ./config/passport-config.js:/config/passport-config.js
