#stage 1
FROM node:alpine3.10
WORKDIR /app
COPY . .
ARG MONGO_POS_URI
ARG STATUS
ARG ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET
ARG SESSION_SECRET
ARG STRIPE_SECRET
RUN npm install
RUN npm run build
CMD ["node","server.js"]
