apiVersion: v1
kind: Secret                #Secret only live in k8s cluster not in repo
metadata:
  name: mongodb-secret
type: Opaque #"Opque" - default for arbitrary key-value pairs (TLS cert)
data:
  mongo-root-username: dXNlcm5hbWU=   #value must be base64 encoded
  mongo-root-password: cGFzc3dvcmQ=  #value must be base64 encoded
