apiVersion: v1
kind: Secret                #Secret only live in k8s cluster not in repo
metadata:
  name: pos-backend-secret
type: Opaque #"Opque" - default for arbitrary key-value pairs (TLS cert)
data:
  session-key: MzU2NDVmNjg2YmFlZjA1MTFlMzdlMWYwMmE0NGFjMGNjYTMzM2Y3YjNkZGEyZTA5MDU4YWM0YjgxZjM2NjZjOTI3NDVmMGI5NTE5ZTFiY2E4YWM1MmZiYzVkMTQwNmQyOWQ4NzBjZTJlZDE2Y2M1ZWRkY2VhMmFmZGMwOTYyMmE= #value must be base64 encoded
  stripe-pk: c2tfdGVzdF9hNXlyQ0ZrZkNrSGNlTGlNRWFabUNvRE4wMHBTQUZrNmVH  #value must be base64 encoded
  access-token-secret: ZWM5ZmRlYzE4NjljNDZhNWI5ZjQyOThkYjk1MmEwNmQ1ZGQ0NGI0MjdiNmM4OTAyYTE0YWE3OGVmZWNmZjExNTg2MDQwMTZkY2FmYWFiYzVjMTIwMzI0OWE2NTZkNjM4YjJjZGE3ZDRhZmRmN2U4ZmQwYzYwOWJkZWJkMGE1ZTk= #value must be base64 encoded
  refresh-token-secret: YWU3OGFjOTEwYmFlZGY4MTgzMWJiNGQ5ZDhmNWJjZDA2Mzc1ZDczZTg1MGJmNjE5N2ZmMTdmOTVjYjExYmYxNGJjZTRhMjUwY2E1ZGQwY2NkZDM3YTA3ODMxN2U4NWE2ZTBjOWEyZDAwNzE2ZWRkY2Y3ZWJiYzIyZjkxYWU4YjU= #value must be base64 encoded


