apiVersion: apps/v1
kind: Deployment                                         #Which Component
metadata:
  name: pos-backend-deployment                                #Name Deployment
  labels:
    app: pos-backend
spec:                                                    #Specification for deployment
  replicas: 2                                            #How Many Replicas
  selector:
    matchLabels:
      app: pos-backend
  template:                                               #Blue print of the pod
    metadata:
      labels:
        app: pos-backend
    spec:                                                 #Specification for pods
      containers:
        - name: pos-backend                                     #1 container inside the pod
          image: mikeycontainer.azurecr.io/pos-backend:latest
          imagePullPolicy: Always                         # 7
          ports:
            - containerPort: 3000 # access port
          env:
            - name: MONGO_POS_URI
              valueFrom:
                configMapKeyRef:
                  name: pos-backend-configmap
                  key: mongo-url
            - name: STATUS
              value: "DEV"
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name:  pos-backend-secret
                  key: stripe-pk
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name:  pos-backend-secret
                  key: refresh-token-secret
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name:  pos-backend-secret
                  key: stripe-pk
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name:  pos-backend-secret
                  key: session-key
---
apiVersion: v1
kind: Service
metadata:
  name: pos-backend-service
spec:
  selector:
    app: pos-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 #ServicePort
      targetPort: 3000 #Containerport


